# Generated by Django 4.2.30 on 2026-08-21 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_age', models.IntegerField()),
                ('person_income', models.IntegerField()),
                ('person_home_ownership', models.CharField(max_length=20)),
                ('person_emp_length', models.FloatField()),
                ('loan_intent', models.CharField(max_length=50)),
                ('loan_grade', models.CharField(max_length=10)),
                ('loan_amnt', models.IntegerField()),
                ('loan_int_rate', models.FloatField()),
                ('loan_percent_income', models.FloatField()),
                ('cb_person_default_on_file', models.CharField(max_length=1)),
                ('cb_person_cred_hist_length', models.IntegerField()),
                ('risk_score', models.FloatField(blank=True, null=True)),
                ('is_high_risk', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
