# Generated by Django 4.2.30 on 2026-08-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_model', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PyTorchBulkResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(max_length=50)),
                ('person_age', models.IntegerField()),
                ('person_income', models.IntegerField()),
                ('loan_amnt', models.IntegerField()),
                ('loan_intent', models.CharField(max_length=50)),
                ('pytorch_risk_score', models.FloatField()),
                ('decision', models.CharField(max_length=20)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='batch_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
